
# Vagrantfile for testing
#
# NOTE: you need the following plugins:
# - `vagrant plugin install vagrant-plugin-bundler --plugin-version 0.1.0`
#
Vagrant::configure("2") do |config|

  # required vagrant plugins
  config.plugin.deps do
    depend 'vagrant-omnibus', '1.0.2'
    depend 'vagrant-cachier', '0.1.0'
    depend 'vagrant-berkshelf', '1.2.0'
  end

  # enable cachier
  config.cache.auto_detect = true
  # the Chef version to use
  config.omnibus.chef_version = "11.4.4"
  # enable berkshelf plugin
  config.berkshelf.enabled = true
  
  #
  # define the sample-app VM
  #
  config.vm.define :"sample-app" do | sample_app_config |
    
    # configure the basebox
    sample_app_config.vm.box = "opscode_ubuntu-13.04_provisionerless"
    sample_app_config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box"
    # configure host-only network
    sample_app_config.vm.hostname = "sample-app-berkshelf.local"
    sample_app_config.vm.network :private_network, ip: "33.33.40.15" 
    # virtualbox customizations
    sample_app_config.vm.provider :virtualbox do |vbox, override|
      vbox.customize ["modifyvm", :id, "--name", "sample-app-berkshelf.local"] 
    end
    
    # provisioning
    sample_app_config.vm.provision :chef_solo do |chef|
      chef.add_recipe "sample-app"
      chef.json = {
        :sample_app => {
          :words_of_wisdom => "Sample App with vagrant-berkshelf Plugin!"
        }
      }
    end
  end 
end
